version: "3.9"

services:
  db:
    image: postgres:15
    container_name: deltafleet_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: deltafleet_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    container_name: deltafleet_web
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: deltafleet_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@deltafleet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
