services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: deltafleet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
